accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "FTL",
    "OFL-1.1",
    "Zlib",
    "AGPL-3.0",
    "BSL-1.0",
    "Unicode-DFS-2016",
    "zlib-acknowledgement",
    "MIT-0",
    "CC0-1.0"
]

targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin"
]